units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 2
  py: ky + 2
  step: .5
  # Wall Padding Variable
  wpx: kx + 3
  wpy: ky + 3
  # Double Padding Variables
  dpx: kx + 6
  dpy: ky + 6
  # Defaults to M2 Screws
  screwSize: 1.5
  standoffSize: 2.5
points:
  zones:
    Main_Board:
      anchor:
        shift: [100, -100]
      key:
        padding: 1ky+1
        spread: 1kx+1
      columns:
        mod:
          key.column_net: P19
        pinky:
          key.column_net: P18
          key.stagger: 2
          key.splay:
        ring:
          key.stagger: 6
          key.column_net: P15
        middle:
          key.stagger: 2.5
          key.column_net: P14
        index:
          key.stagger: -2.5
          key.column_net: P16
        inner:
          key.stagger: -2.5
          key.column_net: P10
      rows:
        bot:
          row_net: P7
        mid:
          row_net: P6
        top:
          row_net: P5
        num:
          row_net: P4
    reach:
      anchor:
        ref: Main_Board_inner_mid
        shift: [1kx + 2step, -0.75ky]
      columns:
        reach:
          key:
            column_net: P10

      rows:
        reach:
          rotate: 0
          row_net: P8
          key:

    thumb:
      anchor:
        ref: Main_Board_inner_bot
        shift: [-2.65kx, -1ky]
      columns:
        tucky1:
          key:
            stagger: -1
            spread: kx+1
            column_net: P15
            #name: thumb_tucky1
        tucky2:
          key:
            spread: kx+1
            column_net: P14
            name: thumb_tucky2
        tucky3:
          key:
            stagger: -2
            spread: kx+1
            column_net: P16
            name: thumb_tucky3
        reachy:

          key:
            stagger: -4
            shift: [0.35kx,1]
            width: 1.5kx
            rotate: -115
            column_net: P10

      rows:
        stretch:
          row_net: P9
          key:
            name: thumb
  mirror: &mirror
    ref: Main_Board_inner_num
    distance: 5.5kx
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
  accuratekeys:
    - what: rectangle
      where: true
      size: [13.80,13.80]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: Main_Board_mod_num
          shift: [-0.55px,0.5py]
        - ref: Main_Board_mod_bot
          shift: [-0.55px,-0.5py]
        - ref: Main_Board_mod_bot
          shift: [-0.1px,-0.65py]
        - ref: thumb_tucky1_stretch
          shift: [-0.5py,-0.7py]
        - ref: thumb_reachy_stretch
          shift: [0.55px,0.95py]
        - ref: reach_reach_reach
          shift: [0.7px,-0.5py]
        - ref: Main_Board_inner_num
          shift: [2px,0.5py]
        - ref: Main_Board_inner_num
          shift: [0.5px,0.5py]
        - ref: Main_Board_middle_num
          shift: [0,0.6py]
        - ref: Main_Board_ring_num
          shift: [-0.5px,0.5py]
      fillet: 2
  InnerWallOutlineL:
    - what: polygon
      operation: stack
      points:
        - ref: Main_Board_mod_num
          shift: [-0.55wpx,0.5wpy]
        - ref: Main_Board_mod_bot
          shift: [-0.55wpx,-0.5wpy]
        - ref: Main_Board_mod_bot
          shift: [-0.1wpx,-0.65wpy]
        - ref: thumb_tucky1_stretch
          shift: [-0.5wpy,-0.7wpy]
        - ref: thumb_reachy_stretch
          shift: [0.55wpx,0.95wpy]
        - ref: reach_reach_reach
          shift: [0.7wpx,-0.5wpy]
        - ref: Main_Board_inner_num
          shift: [2wpx,0.6wpy]
        - ref: Main_Board_inner_num
          shift: [0.5wpx,0.6wpy]
        - ref: Main_Board_middle_num
          shift: [0,0.55wpy]
        - ref: Main_Board_ring_num
          shift: [-0.5wpx,0.5wpy]
      fillet: 2
  BigBoardL:
    - what: polygon
      operation: stack
      points:
        - ref: Main_Board_mod_num
          shift: [-0.55dpx,0.5dpy]
        - ref: Main_Board_mod_bot
          shift: [-0.55dpx,-0.5dpy]
        - ref: Main_Board_mod_bot
          shift: [-0.1dpx,-0.65dpy]
        - ref: thumb_tucky1_stretch
          shift: [-0.5dpy,-0.7dpy]
        - ref: thumb_reachy_stretch
          shift: [0.55dpx,0.95dpy]
        - ref: reach_reach_reach
          shift: [0.7dpx,-0.5dpy]
        - ref: Main_Board_inner_num
          shift: [2dpx,0.6dpy]
        - ref: Main_Board_inner_num
          shift: [0.5dpx,0.6dpy]
        - ref: Main_Board_middle_num
          shift: [0,0.55dpy]
        - ref: Main_Board_ring_num
          shift: [-0.5dpx,0.5dpy]
      fillet: 2
  mounting:
    - what: circle
      radius: screwSize
      where:
        ref: [Main_Board_pinky_num]
        shift: [5, 0.68ky]
    - what: circle
      radius: screwSize
      where:
        ref: [Main_Board_pinky_bot]
        shift: [9, -0.8ky]
    - what: circle
      radius: screwSize
      where:
        ref: [Main_Board_inner_bot]
        shift: [4, -0.85ky]
    - what: circle
      radius: screwSize
      where:
        ref: [Main_Board_inner_num]
        shift: [2+1.75kx,-0.7ky]
  standoff:
    - what: circle
      radius: standoffSize
      where:
        ref: [Main_Board_pinky_num]
        shift: [5, 0.68ky]
    - what: circle
      radius: standoffSize
      where:
        ref: [Main_Board_pinky_bot]
        shift: [9, -0.8ky]
    - what: circle
      radius: standoffSize
      where:
        ref: [Main_Board_inner_bot]
        shift: [4, -0.85ky]
    - what: circle
      radius: standoffSize
      where:
        ref: [Main_Board_inner_num]
        shift: [2+1.75kx,-0.7ky]
  boardR:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_Main_Board_mod_num
          shift: [-0.55px,0.5py]
        - ref: mirror_Main_Board_mod_bot
          shift: [-0.55px,-0.5py]
        - ref: mirror_Main_Board_mod_bot
          shift: [-0.1px,-0.65py]
        - ref: mirror_thumb_tucky1_stretch
          shift: [-0.5py,-0.7py]
        - ref: mirror_thumb_reachy_stretch
          shift: [0.55px,0.95py]
        - ref: mirror_reach_reach_reach
          shift: [0.7px,-0.5py]
        - ref: mirror_Main_Board_inner_num
          shift: [2px,0.5py]
        - ref: mirror_Main_Board_inner_num
          shift: [0.5px,0.5py]
        - ref: mirror_Main_Board_middle_num
          shift: [0,0.6py]
        - ref: mirror_Main_Board_ring_num
          shift: [-0.5px,0.5py]
      fillet: 2
  InnerWallOutlineR:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_Main_Board_mod_num
          shift: [-0.55wpx,0.5wpy]
        - ref: mirror_Main_Board_mod_bot
          shift: [-0.55wpx,-0.5wpy]
        - ref: mirror_Main_Board_mod_bot
          shift: [-0.1wpx,-0.65wpy]
        - ref: mirror_thumb_tucky1_stretch
          shift: [-0.5wpy,-0.7wpy]
        - ref: mirror_thumb_reachy_stretch
          shift: [0.55wpx,0.95wpy]
        - ref: mirror_reach_reach_reach
          shift: [0.7wpx,-0.5wpy]
        - ref: mirror_Main_Board_inner_num
          shift: [2wpx,0.6wpy]
        - ref: mirror_Main_Board_inner_num
          shift: [0.5wpx,0.6wpy]
        - ref: mirror_Main_Board_middle_num
          shift: [0,0.55wpy]
        - ref: mirror_Main_Board_ring_num
          shift: [-0.5wpx,0.5wpy]
      fillet: 2
  BigBoardR:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_Main_Board_mod_num
          shift: [-0.55dpx,0.5dpy]
        - ref: mirror_Main_Board_mod_bot
          shift: [-0.55dpx,-0.5dpy]
        - ref: mirror_Main_Board_mod_bot
          shift: [-0.1dpx,-0.65dpy]
        - ref: mirror_thumb_tucky1_stretch
          shift: [-0.5dpy,-0.7dpy]
        - ref: mirror_thumb_reachy_stretch
          shift: [0.55dpx,0.95dpy]
        - ref: mirror_reach_reach_reach
          shift: [0.7dpx,-0.5dpy]
        - ref: mirror_Main_Board_inner_num
          shift: [2dpx,0.6dpy]
        - ref: mirror_Main_Board_inner_num
          shift: [0.5dpx,0.6dpy]
        - ref: mirror_Main_Board_middle_num
          shift: [0,0.55dpy]
        - ref: mirror_Main_Board_ring_num
          shift: [-0.5dpx,0.5dpy]
      fillet: 2
  mountingR:
    - what: circle
      radius: screwSize
      where:
        ref: [mirror_Main_Board_pinky_num]
        shift: [5, 0.68ky]
    - what: circle
      radius: screwSize
      where:
        ref: [mirror_Main_Board_pinky_bot]
        shift: [9, -0.8ky]
    - what: circle
      radius: screwSize
      where:
        ref: [mirror_Main_Board_inner_bot]
        shift: [4, -0.85ky]
    - what: circle
      radius: screwSize
      where:
        ref: [mirror_Main_Board_inner_num]
        shift: [2+1.75kx,-0.7ky]
  standoffR:
    - what: circle
      radius: standoffSize
      where:
        ref: [mirror_Main_Board_pinky_num]
        shift: [5, 0.68ky]
    - what: circle
      radius: standoffSize
      where:
        ref: [mirror_Main_Board_pinky_bot]
        shift: [9, -0.8ky]
    - what: circle
      radius: standoffSize
      where:
        ref: [mirror_Main_Board_inner_bot]
        shift: [4, -0.85ky]
    - what: circle
      radius: standoffSize
      where:
        ref: [mirror_Main_Board_inner_num]
        shift: [2+1.75kx,-0.7ky]
  boardGrid:
    - what: polygon
      operation: stack
      points:
        - ref: Main_Board_mod_num
          shift: [-0.55px,0.5py]
        - ref: Main_Board_mod_bot
          shift: [-0.55px,-0.5py]
        - ref: Main_Board_mod_bot
          shift: [-0.1px,-0.65py]
        - ref: thumb_tucky1_stretch
          shift: [-0.5py,-0.7py]
        - ref: thumb_reachy_stretch
          shift: [0.55px,0.95py]
        - ref: reach_reach_reach
          shift: [0.7px,-0.5py]
        - ref: reach_reach_reach
          shift: [0.5px, 0.5py]
        - ref: Main_Board_inner_mid
          shift: [0.5px,0]
        - ref: Main_Board_inner_num
          shift: [0.5px,0.5py]
        - ref: Main_Board_middle_num
          shift: [0,0.6py]
        - ref: Main_Board_ring_num
          shift: [-0.5px,0.5py]
      fillet: 2
  Combo:
    - name: boardGrid
    - operation: subtract
      name: accuratekeys
    - operation: subtract
      name: mounting

pcbs:
  MadoSplit:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: 180
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-4, 5]
          rotate: 270
      ProMicro:
        what: promicro
        params:
          orientation: "up"
        where:
          ref: Main_Board_inner_num
          shift: [2+kx,-0.5ky]
          rotate: -90
      holeTopLeft:
        what: mountinghole
        where:
          ref: Main_Board_pinky_num
          shift: [5, 0.68ky]
      holeBotLeft:
        what: mountinghole
        where:
          ref: Main_Board_pinky_bot
          shift: [9, -0.8ky]
      holeBotRight:
        what: mountinghole
        where:
          ref: Main_Board_inner_bot
          shift: [4, -0.85ky]
      holeTopRight:
        what: mountinghole
        where:
          ref: Main_Board_inner_num
          shift: [2+1.75kx,-0.7ky]
      TRRS:
        what: trrs
        params:
          A: GND
          B: GND
          C: P0
          D: VCC
        where:
          ref: Main_Board_inner_num
          shift: [2kx,0.55ky- 0.4]
      Reset:
        what: button
        params:
          from: RST
          to: GND
        where:
          ref: Main_Board_inner_num
          shift: [1+1.75kx,-1.2ky]
          rotate: 90
      Oled:
        what: oled
        params:
          side: "F"
          SDA: P3
          SCL: P2
        where:
          ref: Main_Board_inner_num
          shift: [2+kx-6,-0.5ky-21]
          rotate: 90
  MadoSplitR:
    outlines:
      main:
        outline: boardR
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: 180
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [4, 5]
          rotate: 90
      ProMicro:
        what: promicro
        params:
          orientation: "down"
        where:
          ref: mirror_Main_Board_inner_num
          shift: [2+kx,-0.5ky]
          rotate: 90
      holeTopLeft:
        what: mountinghole
        where:
          ref: mirror_Main_Board_pinky_num
          shift: [5, 0.68ky]
      holeBotLeft:
        what: mountinghole
        where:
          ref: mirror_Main_Board_pinky_bot
          shift: [9, -0.8ky]
      holeBotRight:
        what: mountinghole
        where:
          ref: mirror_Main_Board_inner_bot
          shift: [4, -0.85ky]
      holeTopRight:
        what: mountinghole
        where:
          ref: mirror_Main_Board_inner_num
          shift: [2+1.75kx,-0.7ky]
      TRRS:
        what: trrs
        params:
          A: GND
          B: GND
          C: P0
          D: VCC
        where:
          ref: mirror_Main_Board_inner_num
          shift: [2kx,0.55ky- 0.4]
      Reset:
        what: button
        params:
          from: RST
          to: GND
        where:
          ref: mirror_Main_Board_inner_num
          shift: [1+1.75kx,-1.2ky]
          rotate: 90
      Oled:
        what: oled
        params:
          side: "F"
          SDA: P3
          SCL: P2
        where:
          ref: mirror_Main_Board_inner_num
          shift: [2+kx-6,-0.5ky-21]
          rotate: 90
cases:

  xlBottom:
    - name: BigBoardL
      extrude: 1
  _outerWall:
    - name: BigBoardL
      extrude: 5
  _innerWall:
    - name: InnerWallOutlineL
      extrude: 5
  wall:
    - what: case
      name: _outerWall
      operation: add
    - what: case
      name: _innerWall
      operation: subtract
  _holes:
    - name: mounting
      extrude: 3
  _standoffs:
    - name: standoff
      extrude: 3
  case:
    - what: case
      name: _standoffs
      operation: add
    - what: case
      name: _holes
      operation: subtract
    - what: case
      name: xlBottom
      operation: add
    - what: case
      name: wall
      operation: add
  xlBottomR:
    - name: BigBoardR
      extrude: 1
  _outerWallR:
    - name: BigBoardR
      extrude: 5
  _innerWallR:
    - name: InnerWallOutlineR
      extrude: 5
  wallR:
    - what: case
      name: _outerWallR
      operation: add
    - what: case
      name: _innerWallR
      operation: subtract
  _holesR:
    - name: mountingR
      extrude: 3
  _standoffsR:
    - name: standoffR
      extrude: 3
  caseR:
    - what: case
      name: _standoffsR
      operation: add
    - what: case
      name: _holesR
      operation: subtract
    - what: case
      name: xlBottomR
      operation: add
    - what: case
      name: wallR
      operation: add
  gridKey:
    - name: Combo
      extrude: 2
